---
title: "SPL_difference_statistics"
author: "Marie Zahn"
date: '2023-07-13'
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Calculate SPL difference between target frequency bands

```{r load packages and data}
## load required packages
library(here)
library(ggplot2)
library(PAMpal)
library(dplyr)

#Set time zone to UTC
Sys.setenv(TZ = 'UTC')

## full datasets - updated version of PAMGuard
## load Fisher data
load(here("R/Rdata/1hr/Fish_20kHzPG_0kHzPP_1hr_wavTime_filtered_labeled.rdata"))
## load Kong Oscar data
load(here("R/Rdata/1hr/Kong_20kHzPG_0kHzPP_1hr_wavTime_filtered_labeled.rdata"))
## load training 2013 data
load(here('R/Rdata/Monodontid_2013_data_ch1.rdata'))
```

```{r update Binaries location on path, results = FALSE, include=FALSE}
## 2013 training data
monodontid_2013_data <- updateFiles(Monodontid_2013_data_ch1, bin = 'E:/MS_Chapter_2/PAMGuard/Binaries', db = 'E:/MS_Chapter_2/PAMGuard/PAM20103_Zahn_narluga-ECdetection.sqlite3')
```

```{r calculate third octave levels}
## for Base-ten,
G <- 10**(3/10)

# 16 kHz TOL band ----------
x <- 42 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_16kHz <- G**(-1/6)*freq_m # lower
upper_freq_16kHz <- G**(1/6)*freq_m # upper

# 25 kHz TOL band ----------
x <- 44 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_25kHz <- G**(-1/6)*freq_m # lower
upper_freq_25kHz <- G**(1/6)*freq_m # upper

# 40 kHz TOL band ----------
x <- 46 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_40kHz <- G**(-1/6)*freq_m # lower
upper_freq_40kHz <- G**(1/6)*freq_m # upper
```

Create function to extract TOL band SPL and take mean from average spectra

```{r avgSpec SPL calculations function}
## option to apply a highpass filter but here I do not apply one
## calculates avg spectrum then extracts SPL within frequency bands and calculates difference

avgSpec_band_diff <- function(Acoustic_Study, evNum, clipping_level, filterfrom_khz) {
  ## calculate spectra for narwhal events
  avSpec_all <- calculateAverageSpectra(Acoustic_Study,wl=512,evNum=evNum,
                                        plot=FALSE,sort=FALSE,noise=FALSE,
                                        filterfrom_khz = filterfrom_khz,norm=FALSE)
  
  ## extract frequency values and mean spectra
  freq <- avSpec_all$freq
  avgSpec <- avSpec_all$avgSpec
  
  ## extract spectral data for specified TOL band
  ## 173 is our system clipping level for SoundTraps
  ## 206 is the clipping level for the Reson hydrophones
  band_15to17kHz_dB <- (avgSpec[which(freq>15000 & freq<17000)]+clipping_level) # 15-17 kHz band
  band_22to24kHz_dB <- (avgSpec[which(freq>22000 & freq<24000)]+clipping_level) # 22-24 kHz band
  band_45to47kHz_dB <- (avgSpec[which(freq>45000 & freq<47000)]+clipping_level) # 45-47 kHz band
  
  band_16kHz_dB <- (avgSpec[which(freq>lower_freq_16kHz & freq<upper_freq_16kHz)]+clipping_level) # 16 kHz TOL
  band_25kHz_dB <- (avgSpec[which(freq>lower_freq_25kHz & freq<upper_freq_25kHz)]+clipping_level) # 25 kHz TOL
  band_40kHz_dB <- (avgSpec[which(freq>lower_freq_40kHz & freq<upper_freq_40kHz)]+clipping_level) # 40 kHz TOL
  
  ## because dB is on a log scale, we must convert to linear scale and then take the mean
  ## after taking the mean, we can convert back to log scale
  band_15to17kHz_mean_dB <- 20*log10(mean(10^(band_15to17kHz_dB/20))) # 15-17 kHz band
  band_22to24kHz_mean_dB <- 20*log10(mean(10^(band_22to24kHz_dB/20))) # 22-24 kHz band
  band_45to47kHz_mean_dB <- 20*log10(mean(10^(band_45to47kHz_dB/20))) # 45-47 kHz band
  
  band_16kHz_mean_dB <- 20*log10(mean(10^(band_16kHz_dB/20))) # 16 kHz TOL
  band_25kHz_mean_dB <- 20*log10(mean(10^(band_25kHz_dB/20))) # 25 kHz TOL
  band_40kHz_mean_dB <- 20*log10(mean(10^(band_40kHz_dB/20))) # 40 kHz TOL
  
  ## calculate difference between freq bands
  spl_diff_16to23_dB <- band_22to24kHz_mean_dB - band_15to17kHz_mean_dB
  spl_diff_23to46_dB <- band_45to47kHz_mean_dB - band_22to24kHz_mean_dB
  
  spl_diff_16to25_TOL_dB <- band_25kHz_mean_dB - band_16kHz_mean_dB
  spl_diff_25to40_TOL_dB <- band_40kHz_mean_dB - band_25kHz_mean_dB
  
  ## calculate how many unique clicks are in the dataset
  n_clicks <- nClicks(Acoustic_Study@events[[evNum]], distinct=TRUE) 
  
  ## save mean spectrum
  df_avgSpec <- data.frame(t(avgSpec))
  
  ## extract species ID
  species_id <- Acoustic_Study@events[[evNum]]@species[["id"]]
  
  ## build dataframe with SPL difference and click number data
  df_SPL_diff <- data.frame(eventId=evNum,
                            species=species_id,
                            spl_diff_16to23_dB=spl_diff_16to23_dB, 
                            spl_diff_23to46_dB=spl_diff_23to46_dB,
                            spl_diff_16to25_TOL_dB=spl_diff_16to25_TOL_dB, 
                            spl_diff_25to40_TOL_dB=spl_diff_25to40_TOL_dB,
                            n_dets=n_clicks)
  
  ## join both dataframes
  event_spec_df <- cbind(df_SPL_diff, df_avgSpec)
  
  return(event_spec_df)
}

```

```{r function to loop through events}
# function to loop through each event and get SPL difference between bands

calculate_SPL_diff <- function(Acoustic_Study, clipping_level, filterfrom_khz) {
  # create empty data frame to fill
  band_diff_df <- data.frame(eventId=c(),species=c(),
                             spl_diff_16to23_dB=c(),spl_diff_23to46_dB=c(),
                             spl_diff_16to25_TOL_dB=c(),spl_diff_25to40_TOL_dB=c(),
                             n_dets=c())
  
  for (i in 1:length(Acoustic_Study@events)) {
    # run function to calculate SPL differences
    band_diff_df_tmp <- avgSpec_band_diff(Acoustic_Study, evNum=Acoustic_Study@events[[i]]@id, 
                                          clipping_level, filterfrom_khz)
    # append dataframe
    band_diff_df <- rbind(band_diff_df, band_diff_df_tmp)
  }
  return(band_diff_df)
}

```

```{r run functions for model input}
## 2013 training data ---------------------------
training_data_spl_df <- calculate_SPL_diff(monodontid_2013_data, clipping_level=206, filterfrom_khz=0)
## save output
write.csv(training_data_spl_df, 
          here('R/spreadsheets/SPL_difference/model_input/training_data_spl_diff.csv'),
          row.names = FALSE)

## testing data ---------------------------
## Fisher Islands
testing_fish_data_spl_df <- calculate_SPL_diff(fish_dets_0kHzPP_filter, clipping_level=173, filterfrom_khz=0)
## save output
write.csv(testing_fish_data_spl_df, 
          here('R/spreadsheets/SPL_difference/model_input/testing_fish_data_spl_diff_0kHz_highpass.csv'),
          row.names = FALSE)

## Kong Oscar
testing_kong_data_spl_df <- calculate_SPL_diff(kong_dets_0kHzPP_filter, clipping_level=173, filterfrom_khz=0)
## save output
write.csv(testing_kong_data_spl_df, 
          here('R/spreadsheets/SPL_difference/model_input/testing_kong_data_spl_diff_0kHz_highpass.csv'),
          row.names = FALSE)

```

# Export noise spectra for all events

```{r extract avgSpec noise function}
avgSpec_noise <- function(Acoustic_Study, evNum, clipping_level, wl) {
  ## calculate spectra for narwhal events
  avSpec_all <- calculateAverageSpectra(Acoustic_Study,wl=wl,evNum=evNum,
                                        plot=FALSE,sort=FALSE,noise=FALSE,
                                        filterfrom_khz = 0,norm=FALSE)
  
  ## extract frequency values and mean noise spectra
  freq <- avSpec_all$freq
  avgSpec_noise <- avSpec_all$avgNoise
  
  ## save mean spectrum
  df_avgSpec <- data.frame(t(avgSpec_noise))

  ## build dataframe with event number and species
  df_noise_meta <- data.frame(eventId=evNum,
                              species=Acoustic_Study@events[[evNum]]@species[["id"]])
  
  ## join both dataframes
  noise_event_spec_df <- cbind(df_noise_meta, df_avgSpec)
  
  return(noise_event_spec_df)
}

```

```{r function to loop through events}
# function to loop through each event and get noise spectrum
get_noise_spec <- function(Acoustic_Study, clipping_level, wl) {
  # create empty data frame to fill
  noise_spec_df <- data.frame(eventId=c(),species=c())
  
  for (i in 1:length(Acoustic_Study@events)) {
    # run function to calculate SPL differences
    noise_event_spec_df_tmp <- avgSpec_noise(Acoustic_Study, evNum=Acoustic_Study@events[[i]]@id, 
                                          clipping_level, wl=wl)
    # append dataframe
    noise_spec_df <- rbind(noise_spec_df, noise_event_spec_df_tmp)
  }
  return(noise_spec_df)
}

```

```{r run functions for model input}
## 2013 training data ---------------------------
training_data_noise_df <- get_noise_spec(monodontid_2013_data, clipping_level=206, wl=512)
## save output
write.csv(training_data_noise_df, 
          here('R/spreadsheets/noise_spec/reson_avg_noise_spec.csv'),
          row.names = FALSE)

## testing data ---------------------------
## Fisher Islands
## select only whale events
fish_dets_whale_filter <- fish_dets_0kHzPP_filter %>% filter(species!='NOISE')
testing_fish_data_noise_df <- get_noise_spec(fish_dets_whale_filter, clipping_level=173, wl=256)
## save output
write.csv(testing_fish_noise_df, 
          here('R/spreadsheets/noise_spec/fish_avg_noise_spec.csv'),
          row.names = FALSE)

## Kong Oscar
## select only whale events
kong_dets_whale_filter <- kong_dets_0kHzPP_filter %>% filter(species!='NOISE')
testing_kong_data_noise_df <- get_noise_spec(kong_dets_whale_filter, clipping_level=173, wl=256)
## save output
write.csv(testing_kong_data_noise_df, 
          here('R/spreadsheets/noise_spec/kong_avg_noise_spec.csv'),
          row.names = FALSE)

```
