---
title: "Random Forest"
output: pdf_document
date: "2023-07-25"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
## load required packages
library(here)
library(ggplot2)
library(PAMpal)
library(dplyr)
library(tidyr)
library(randomForest)
library(rfPermute)
```

# Load Data

```{r use SPL difference - pooled data}
fish_test_data <- read.csv(here("R/spreadsheets/SPL_difference/model_input/testing_fish_data_spl_diff_0kHz_highpass.csv"))
kong_test_data <- read.csv(here("R/spreadsheets/SPL_difference/model_input/testing_kong_data_spl_diff_0kHz_highpass.csv"))

## select columns we need
fish_test_data_select <- fish_test_data %>% 
  select(c(species,eventId,spl_diff_16to23_dB,spl_diff_23to46_dB,
           spl_diff_16to25_TOL_dB,spl_diff_25to40_TOL_dB)) %>%
  filter(species!='NOISE')
kong_test_data_select <- kong_test_data %>% 
  select(c(species,eventId,spl_diff_16to23_dB,spl_diff_23to46_dB,
           spl_diff_16to25_TOL_dB,spl_diff_25to40_TOL_dB)) %>% 
  filter(species!='NOISE')

SPL_diff_df_all <- rbind(fish_test_data_select,kong_test_data_select)
```

```{r confusionMatrix func}
## modified code from rfPermute confusionMatrix func
## function to calculate prediction interval from output of predict() function
confusionMatrix_predict <- function(predict_output, SPL_diff_df) {
  ## make confusion matrix
  cm <- table(SPL_diff_df[,1], predict_output)
  
  # binomial test
  conf.level = 0.95
  threshold = NULL
  
  # Confusion matrix and counts
  # cm <- .confMat(rf)
  class.n <- rowSums(cm)
  all.n <- c(class.n, Overall = sum(class.n))
  total.n <- sum(class.n)
  correct.n <- diag(cm)
  correct.n <- c(correct.n, Overall = sum(correct.n))
    
  # Confidence intervals
  ci <- t(sapply(
    mapply(
      stats::binom.test, 
      x = correct.n, 
      n = all.n, 
      p = correct.n / all.n, 
      conf.level = conf.level,
      SIMPLIFY = FALSE
    ),
    function(x) x$conf.int * 100
  ))
  colnames(ci) <- paste(c("LCI", "UCI"), conf.level, sep = "_")
  
  # Probability threshold
  prob.gt <- NULL
  if(!is.null(threshold)) {
    prob.gt <- lapply(threshold, function(p) {
      stats::pbinom(correct.n, total.n, p)
    })
    prob.gt <- do.call(cbind, prob.gt)
    colnames(prob.gt) <- paste0("Pr.gt_", threshold)
  }
  
  cm <- rbind(cm, Overall = rep(NA, ncol(cm)))
  pct.correct <- (correct.n / all.n) * 100
  cbind(
    cm, 
    pct.correct = pct.correct[rownames(cm)], 
    ci[rownames(cm), , drop = FALSE],
    prob.gt
  )
}

```


```{r RF sensitivity analysis function}
## run the RF model over all combinations of sampsize

RF_sampsize_sensitivity_tol <- function(SPL_diff_df) {
  ## make master df with all possible combinations of sampsize
  sampsize_max <- length(SPL_diff_df$species[SPL_diff_df$species=='X045'])-1
  sampsize <- c(2:sampsize_max)
  
  ## loop over all possible combinations
  master_df <- as.data.frame(matrix(nrow = length(sampsize), ncol = 1))
  yy <- SPL_diff_df$species
  
  for (i in 1:length(sampsize)){
    ranfor <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB,
                           data = SPL_diff_df, 
                           ntree = 10000, 
                           importance = TRUE,
                           replace = FALSE,
                           sampsize = rep(sampsize[i],2),
                           proximity = TRUE)
    
    ## calculate accuracy
    rfpred <- predict(ranfor)
    accuracy <- caret::confusionMatrix(rfpred, yy)
    master_df[i,1] <- accuracy$overall[1]
    
  }
  
  ## combine dfs
  sensitivity <- cbind(sampsize, master_df)
  print(sensitivity)
  
  ## calculate % range of model output
  max(sensitivity$V1) - min(sensitivity$V1)
}

```

# Build randomForests for SoundTrap and Reson data

```{r randomForest for soundtrap data}
## make sure species is a factor
SPL_diff_df_all$species <- as.factor(SPL_diff_df_all$species)

## Run random forest model with TOL frequency bands
## calculate sampsize as half the sample size of the smaller species class (=beluga)
rf_sampsize <- ceiling(length(SPL_diff_df_all$species[SPL_diff_df_all$species=='X045'])/2)

ranfor_soundtrap_spl_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB,
                                         data = SPL_diff_df_all, 
                                         ntree = 10000, 
                                         importance = TRUE,
                                         replace = FALSE,
                                         sampsize = c(rf_sampsize,rf_sampsize),
                                         proximity = TRUE)

ranfor_soundtrap_spl_tol
confusionMatrix(ranfor_soundtrap_spl_tol)

## calculate accuracy and sensitivity to sampsize parameter
RF_sampsize_sensitivity_tol(SPL_diff_df_all)
# accuracy varies by <0.5%

## other model diagnostics
plotTrace(ranfor_soundtrap_spl_tol)
plotVotes(ranfor_soundtrap_spl_tol)
varImpPlot(ranfor_soundtrap_spl_tol)
importance(ranfor_soundtrap_spl_tol)
casePredictions(ranfor_soundtrap_spl_tol)

## look at one narwhal event that was misclassified
predictions <- casePredictions(ranfor_soundtrap_spl_tol)
predictions[predictions$is.correct==FALSE,]
SPL_diff_df_all[predictions$is.correct==FALSE,] # event 757


## Run random forest model with selected frequency bands
## calculate sampsize as half the sample size of the smaller species class (=beluga)
rf_sampsize <- ceiling(length(SPL_diff_df_all$species[SPL_diff_df_all$species=='X045'])/2)

ranfor_soundtrap_spl <- randomForest(species ~ spl_diff_16to23_dB + spl_diff_23to46_dB,
                                     data = SPL_diff_df_all, 
                                     ntree = 10000, 
                                     importance = TRUE,
                                     replace = FALSE, 
                                     sampsize = c(rf_sampsize,rf_sampsize),
                                     proximity = TRUE)

ranfor_soundtrap_spl
confusionMatrix(ranfor_soundtrap_spl)

## other model diagnostics
plotTrace(ranfor_soundtrap_spl)
pctCorrect(ranfor_soundtrap_spl)
varImpPlot(ranfor_soundtrap_spl)

```

```{r randomForest for reson data}
## load training 2013 data with SPL calculations
train_data <- read.csv(here("R/spreadsheets/SPL_difference/model_input/training_data_spl_diff.csv"))

## select columns we need
train_spl_data <- train_data %>% select(c(species,eventId,spl_diff_16to23_dB,spl_diff_23to46_dB,
                                          spl_diff_16to25_TOL_dB,spl_diff_25to40_TOL_dB))

## modify species code to match testing dataset
train_spl_data$species[train_spl_data$species==85] <- 'X085'
train_spl_data$species[train_spl_data$species==45] <- 'X045'

## make sure species is a factor
train_spl_data$species <- as.factor(train_spl_data$species)

## run random forest model with TOL frequency bands
ranfor_reson_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB, 
                       data = train_spl_data, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize,rf_sampsize), 
                       proximity = TRUE)

ranfor_reson_tol
confusionMatrix(ranfor_reson_tol)

## calculate accuracy and sensitivity to sampsize parameter
RF_sampsize_sensitivity_tol(train_spl_data)
# accuracy varies by <2.5%

## other model diagnostics
casePredictions(ranfor_reson_tol)
predictions <- casePredictions(ranfor_reson_tol)
train_spl_data[predictions$is.correct==FALSE,] # event 757
varImpPlot(ranfor_reson_tol)

## run random forest model with target frequency bands
## calculate sampsize as half the sample size of the smaller species class (=beluga)
rf_sampsize <- ceiling(length(train_spl_data$species[train_spl_data$species=='X045'])/2)

ranfor_reson <- randomForest(species ~ spl_diff_16to23_dB + spl_diff_23to46_dB, 
                       data = train_spl_data, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize,rf_sampsize), 
                       proximity = TRUE)

ranfor_reson
confusionMatrix(ranfor_reson)

## other model diagnostics
plotTrace(ranfor_reson)
plotVotes(ranfor_reson)
casePredictions(ranfor_reson)
varImpPlot(ranfor_reson)

```

# Build model with pooled Reson and SoundTrap detections

```{r Reson and SoundTrap model}
# combine Reson and ST datasets
spl_reson_soundtrap <- rbind(train_spl_data, SPL_diff_df_all)

## make sure species is a factor
spl_reson_soundtrap$species <- as.factor(spl_reson_soundtrap$species)

rf_sampsize <- ceiling(length(spl_reson_soundtrap$species[spl_reson_soundtrap$species=='X045'])/2)

## run random forest model with TOL frequency bands
ranfor_reson_soundtrap_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB, 
                       data = spl_reson_soundtrap, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize,rf_sampsize), 
                       proximity = TRUE)

ranfor_reson_soundtrap_tol
confusionMatrix(ranfor_reson_soundtrap_tol)

## calculate accuracy and sensitivity to sampsize parameter
RF_sampsize_sensitivity_tol(spl_reson_soundtrap)


## run random forest model with target frequency bands
ranfor_reson_soundtrap <- randomForest(species ~ spl_diff_16to23_dB + spl_diff_23to46_dB, 
                       data = spl_reson_soundtrap, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize,rf_sampsize), 
                       proximity = TRUE)

ranfor_reson_soundtrap
confusionMatrix(ranfor_reson_soundtrap)

```


# SoundTrap and Reson data predictions

```{r use reson data to predict SoundTrap}
## model with specific frequency band vars
## make sure species is a factor
SPL_diff_df_all$species <- as.factor(SPL_diff_df_all$species)

## model with TOL vars
y_pred_reson_tol <- predict(ranfor_reson_tol, newdata=SPL_diff_df_all[,5:6], type='pred')
confusionMatrix_predict(y_pred_reson_tol,SPL_diff_df_all)

## model with specific freq bands
# y_pred <- predict(ranfor_reson, newdata=SPL_diff_df_all[,2:3], type='prob') # to get votes for each event
y_pred_reson <- predict(ranfor_reson, newdata=SPL_diff_df_all[,3:4])
confusionMatrix_predict(y_pred_reson,SPL_diff_df_all)

```

```{r use SoundTrap to predict reson}
## model with tol bands
y_pred_soundtrap_tol <- predict(ranfor_soundtrap_spl_tol, newdata=train_spl_data[,5:6])
confusionMatrix_predict(y_pred_soundtrap_tol,train_spl_data)

## model with specific freq bands
y_pred_soundtrap <- predict(ranfor_soundtrap_spl, newdata=train_spl_data[,3:4])
confusionMatrix_predict(y_pred_soundtrap,train_spl_data)

```

# RF models for Fisher and Kong

```{r run separate RF models for Fisher and Kong}
## make sure species is a factor
fish_test_data_select$species <- as.factor(fish_test_data_select$species)
kong_test_data_select$species <- as.factor(kong_test_data_select$species)

## calculate sampsize as half the sample size of the smaller species class (=beluga)
rf_sampsize_fish <- ceiling(length(fish_test_data_select$species[fish_test_data_select$species=='X045'])/2)
rf_sampsize_kong <- ceiling(length(kong_test_data_select$species[kong_test_data_select$species=='X045'])/2)

## Fisher Islands 

## run random forest model - TOL
ranfor_fish_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB, 
                       data = fish_test_data_select, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize_fish,rf_sampsize_fish), 
                       proximity = TRUE)

ranfor_fish_tol
confusionMatrix(ranfor_fish_tol)

## calculate accuracy and sensitivity to sampsize parameter
RF_sampsize_sensitivity_tol(fish_test_data_select)
# accuracy varies by <0.9%

## run random forest model
ranfor_fish <- randomForest(species ~ spl_diff_16to23_dB + spl_diff_23to46_dB, 
                       data = fish_test_data_select, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize_fish,rf_sampsize_fish), 
                       proximity = TRUE)

ranfor_fish
confusionMatrix(ranfor_fish)

## Kong Oscar 

## run random forest model - TOL
ranfor_kong_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB, 
                       data = kong_test_data_select, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize_kong,rf_sampsize_kong), 
                       proximity = TRUE)

ranfor_kong_tol
confusionMatrix(ranfor_kong_tol)

## calculate accuracy and sensitivity to sampsize parameter
RF_sampsize_sensitivity_tol(kong_test_data_select)
# accuracy varies by 0%

## run random forest model
ranfor_kong <- randomForest(species ~ spl_diff_16to23_dB + spl_diff_23to46_dB, 
                       data = kong_test_data_select, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize_kong,rf_sampsize_kong),
                       proximity = TRUE)

ranfor_kong
confusionMatrix(ranfor_kong)

```

```{r Use one dataset to predict the other}
## with TOL bands
## fisher predicts kong
y_pred_kong_tol <- predict(ranfor_fish_tol, newdata=kong_test_data_select[,5:6])
confusionMatrix_predict(y_pred_kong_tol,kong_test_data_select)
## kong predicts fisher
y_pred_fish_tol <- predict(ranfor_kong_tol, newdata=fish_test_data_select[,5:6])
confusionMatrix_predict(y_pred_fish_tol,fish_test_data_select)

## with selected freq bands
## fisher predicts kong
y_pred_kong <- predict(ranfor_fish, newdata=kong_test_data_select[,3:4])
confusionMatrix_predict(y_pred_kong,kong_test_data_select)
## kong predicts fisher
y_pred_fish <- predict(ranfor_kong, newdata=fish_test_data_select[,3:4])
confusionMatrix_predict(y_pred_fish,fish_test_data_select)
```

# Asses variable importance and percent votes

```{r plotAssignments from rfPermute}
# forked code from Eric Archer's gtihub swfscMisc
plotAssignments <- function(
  probs, orig, type = NULL, ylab = NULL, freq.sep.line = TRUE, plot = TRUE
) {
  freq <- table(orig)
  type <- if(is.null(type)) {
    if(all(freq <= 30)) "bar" else "area"
  } else {
    match.arg(type, c("bar", "area"))
  }
  
  if(is.null(colnames(probs))) {
    colnames(probs) <- paste("Group", 1:ncol(probs), sep = ".")
  }
  
  df <- data.frame(orig = orig, probs, check.names = FALSE)
  i <- do.call(order, c(as.list(df), list(decreasing = TRUE)))
  df <- df[i, ] %>% 
    dplyr::mutate(id = 1:dplyr::n()) %>% 
    tidyr::pivot_longer(-c("id", "orig"), names_to = "pred", values_to = "prob")
  if(!is.null(freq.sep.line)) {
    levels(df$orig) <- paste0(
      names(freq), ifelse(freq.sep.line, "\n", " "), "(n = ", freq, ")"
    )
  }
  
  if(is.null(ylab)) ylab <- "Assignment Probability"
  
  p <- ggplot2::ggplot(df, ggplot2::aes_string("id", "prob")) +
    switch(
      type,
      area = ggplot2::geom_area(
        ggplot2::aes_string(fill = "pred"), 
        stat = "identity"
      ),
      bar = ggplot2::geom_bar(
        ggplot2::aes_string(fill = "pred"), 
        stat = "identity"
      )
    ) +
    ggplot2::scale_fill_discrete(
      guide = ggplot2::guide_legend(title = "Predicted")
    ) +
    ggplot2::scale_x_continuous(expand = c(0, 0)) +
    ggplot2::scale_y_continuous(expand = c(0, 0)) +
    ggplot2::facet_wrap(~ orig, scales = "free_x") +
    ggplot2::ylab(ylab) +
    ggplot2::theme(
      legend.position = "top",
      text = ggplot2::element_text(size = 14),
      axis.text.x = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(hjust = 0),
      panel.grid = ggplot2::element_blank(),
      panel.background = ggplot2::element_blank()
    )
  if(plot) print(p)
  invisible(p)
}
```

```{r importance scores and plotVotes}
## look at which variable is most important for species classification

# model development
importance(ranfor_soundtrap_spl_tol)
importance(ranfor_reson_tol)
importance(ranfor_reson_soundtrap_tol)
importance(ranfor_fish_tol)
importance(ranfor_kong_tol)

## plot Votes to assess overall model confidence in predictions
# model development
plotVotes(ranfor_soundtrap_spl_tol)
plotVotes(ranfor_reson_tol)
plotVotes(ranfor_reson_soundtrap_tol)
plotVotes(ranfor_fish_tol)
plotVotes(ranfor_kong_tol)

# model predictions
y_pred_reson_tol <- predict(ranfor_reson_tol, newdata=SPL_diff_df_all[,5:6], type='prob')
y_pred_soundtrap_tol <- predict(ranfor_soundtrap_spl_tol, newdata=train_spl_data[,5:6], type='prob')
y_pred_kong_tol <- predict(ranfor_fish_tol, newdata=kong_test_data_select[,5:6], type='prob')
y_pred_fish_tol <- predict(ranfor_kong_tol, newdata=fish_test_data_select[,5:6], type='prob')

# plotVotes of model predictions
# reson to predict soundtrap
plotAssignments((y_pred_reson_tol/rowSums(y_pred_reson_tol))*100,
                SPL_diff_df_all$species,ylab = "Percent of votes")
# soundtrap to predict reson
plotAssignments((y_pred_soundtrap_tol/rowSums(y_pred_soundtrap_tol))*100,
                train_spl_data$species,ylab = "Percent of votes")

plotAssignments((y_pred_kong_tol/rowSums(y_pred_kong_tol))*100,
                kong_test_data_select$species,ylab = "Percent of votes")

plotAssignments((y_pred_fish_tol/rowSums(y_pred_fish_tol))*100,
                fish_test_data_select$species,ylab = "Percent of votes")

```

```{r export example plot votes fig for supplement}
# first change species codes to species names
levels(spl_reson_soundtrap$species) <- c("Beluga","Narwhal")

## run random forest model with TOL frequency bands
ranfor_reson_soundtrap_tol <- randomForest(species ~ spl_diff_16to25_TOL_dB + spl_diff_25to40_TOL_dB, 
                       data = spl_reson_soundtrap, 
                       ntree = 10000, 
                       importance = TRUE,
                       replace = FALSE,
                       sampsize = c(rf_sampsize,rf_sampsize), 
                       proximity = TRUE)

plotVotes_ex <- plotVotes(ranfor_reson_soundtrap_tol)
ggsave(here("R/figures/plotVotes_example.png"), dpi=300)

# PlotVotes example of poor predictions
# soundtrap to predict reson
levels(train_spl_data$species) <- c("Beluga","Narwhal")
colnames(y_pred_soundtrap_tol) <- c("Beluga","Narwhal")

plotAssignments((y_pred_soundtrap_tol/rowSums(y_pred_soundtrap_tol))*100,
                train_spl_data$species,ylab = "Percent of votes")

ggsave(here("R/figures/plotVotes_ST-pred-reson.png"), dpi=300)

# reson predicts soundtrap
levels(SPL_diff_df_all$species) <- c("Beluga","Narwhal")
colnames(y_pred_reson_tol) <- c("Beluga","Narwhal")

plotAssignments((y_pred_reson_tol/rowSums(y_pred_reson_tol))*100,
                SPL_diff_df_all$species,ylab = "Percent of votes")

ggsave(here("R/figures/plotVotes_reson-pred-ST.png"), dpi=300)

```

