---
title: "Add noise category to classifier"
editor_options: 
  chunk_output_type: console
---

```{r set up workspace}
## load required packages
library(ggplot2)
library(PAMpal)
library(banter)
library(dplyr)
library(randomForest)
library(rfPermute)
library(here)
```

```{r load data}
## load training data from 2013
load(file=here('R/Rdata/Monodontid_2013_data_ch1.rdata'))

## load noise subset from Fisher Islands mooring
load(file=here('R/Rdata/noise/Fisher_noise_20kHzPG_20kHzPP_1hr_wavTime.rdata'))

## load noise subset from Kong Oscar mooring
load(file=here('R/Rdata/noise/Kong_noise_20kHzPG_20kHzPP_1hr_wavTime.rdata'))

```

# Add noise to 2013 whale dataset

```{r merge noise dataset with training data whale detections}
## Merge datasets before putting into 'export_banter'
banterAll_noise <- export_banter(c(events(Monodontid_2013_data_ch1),
                                   events(fisher_noise_filter), 
                                   events(kong_noise_filter)),
                                 dropVars = c('noiseLevel', 'dBPP', 
                                            'peakTime', 'Click_Detector_2_ici'))

save(banterAll_noise, file=here('R/Rdata/banterAll_noise_20kHzhighpass.rdata'))

```

# rerun BANTER model with noise - only Det 2

```{r rerun Banter training model - Only Det2}
## initialize banter model
bant.mdl_noise <- initBanterModel(banterAll_noise$events)

## look at detector names and order
names(banterAll_noise$detectors)

## run RF models for each Detector added-------------------------------------
bant.mdl_noise <- addBanterDetector(
  bant.mdl_noise, 
  data = banterAll_noise$detectors[2], # includes only Detector 2 
  ntree = 10000, 
  sampsize = 50,
  importance = TRUE
)
## look at summary of Detector models
## this shows correct classification rate for each species/category in each detector
summary(bant.mdl_noise)
plotDetectorTrace(bant.mdl_noise)

## run Event model------------------------------------------------------------
bant.mdl_noise <- runBanterModel(bant.mdl_noise, ntree = 10000, sampsize = 9)

## look at summary for Event model
summary(bant.mdl_noise)

## get RF data from banter model
event.rf_noise <- getBanterModel(bant.mdl_noise, "event")

## SUMMARIES
plotVotes(event.rf_noise)
plotProximity(event.rf_noise)
casePredictions(event.rf_noise)

## OTHER THINGS TO LOOK INTO: -------------------------------
## get RF data for specific detector - example of Det 5:
(event.rf.Det4 <- getBanterModel(bant.mdl_new, "Click_Detector_4"))

## examine model stability
rfPermute::plotTrace(event.rf)
rfPermute::plotInbag(event.rf)

## get predictor names for event level RF model
colnames(bant.mdl_new@model.data)

save(bant.mdl_noise, file='Rdata/bant_mdl_Det2_noise.rdata')
# save(banterAll_new, file='Rdata/banterAll_Det2.rdata')

# load(file.choose())

```

# rerun BANTER model with noise - Dets 2 and 3

```{r rerun Banter training model - Det2 and Det3}
## export banter model
load(file=here('R/Rdata/banterAll_noise.rdata'))

## initialize banter model
bant.mdl_noise <- initBanterModel(banterAll_noise$events)

## look at detector names and order
names(banterAll_noise$detectors)

## run RF models for each Detector added-------------------------------------
bant.mdl_noise <- addBanterDetector(
  bant.mdl_noise, 
  data = banterAll_noise$detectors[c(2,3)], # includes only Detectors 2 and 3
  ntree = 10000, 
  sampsize = 50,
  importance = TRUE
)

## look at summary of Detector models
## this shows correct classification rate for each species/category in each detector
summary(bant.mdl_noise)
plotDetectorTrace(bant.mdl_noise)

## run Event model------------------------------------------------------------
bant.mdl_noise <- runBanterModel(bant.mdl_noise, ntree = 10000, sampsize = 9)

## look at summary for Event model
summary(bant.mdl_noise)

## get RF data from banter model
event.rf_noise <- getBanterModel(bant.mdl_noise, "event")

## SUMMARIES
plotVotes(event.rf_noise)
plotProximity(event.rf_noise)
casePredictions(event.rf_noise)

## examine model stability
rfPermute::plotTrace(event.rf_noise)
rfPermute::plotInbag(event.rf_noise)

## get predictor names for event level RF model
colnames(bant.mdl_new@model.data)

save(bant.mdl_noise, file=here('R/Rdata/bant_mdl_Det23_20kHz_noise.rdata'))

```
