---
title: "03_update_classifier"
output: pdf_document
date: "2023-07-31"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up workspace}
## load required packages
library(ggplot2)
library(PAMpal)
library(banter)
library(dplyr)
library(here)

#Set time zone to UTC
Sys.setenv(TZ = 'UTC')

## install PAMpal package from GitHub
# devtools::install_github('TaikiSan21/PAMpal')
## install BANTER package from GitHub
# devtools::install_github('ericarcher/banter')

```

```{r load data}
## model without noise category
load(file=here('R/Rdata/banterAll_new.rdata'))
load(file=here('R/Rdata/bant_mdl_new.rdata'))

## load data
# load(file='Rdata/Fisher_2019.rdata')
load(file='Rdata/Fisher_2019_20kHz.rdata')
load(file='Rdata/Monodontid_2013_data_ch1.rdata')

## load testing data
## version with updated version of PAMGuard
load(here("R/Rdata/1hr/Fish_20kHzPG_20kHzPP_1hr_wavTime_filtered_labeled.rdata"))
load(here("R/Rdata/1hr/Kong_20kHzPG_20kHzPP_1hr_wavTime_filtered_labeled.rdata"))

```

```

