---
title: "TOL bands"
author: "Marie Zahn"
date: "2023-08-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## load required packages
library(here)
library(ggplot2)
library(PAMpal)
library(dplyr)
```


```{r calculate third octave levels}
## for Base-ten,
G <- 10**(3/10)

# 16 kHz TOL band ----------
x <- 42 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_16kHz <- G**(-1/6)*freq_m # lower
upper_freq_16kHz <- G**(1/6)*freq_m # upper

# 25 kHz TOL band ----------
x <- 44 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_25kHz <- G**(-1/6)*freq_m # lower
upper_freq_25kHz <- G**(1/6)*freq_m # upper

# 40 kHz TOL band ----------
x <- 46 # band number
# midband frequency
(freq_m <- (G**((x-30)/3)*1000))
# calculate bandedge frequencies
lower_freq_40kHz <- G**(-1/6)*freq_m # lower
upper_freq_40kHz <- G**(1/6)*freq_m # upper
```


```{r practice TOL calculation}
# open dataset

## load Fisher data
load(here("R/Rdata/1hr/Fish_20kHzPG_0kHzPP_1hr_wavTime_filtered_labeled.rdata"))

avgSpec_band_diff <- function(Acoustic_Study, evNum, clipping_level, filterfrom_khz) {
  ## calculate spectra for narwhal events
  avSpec_all <- calculateAverageSpectra(Acoustic_Study,wl=512,evNum=evNum,
                                        plot=FALSE,sort=FALSE,noise=FALSE,
                                        filterfrom_khz = filterfrom_khz,norm=FALSE)
  
  ## extract frequency values and mean spectra
  freq <- avSpec_all$freq
  avgSpec <- avSpec_all$avgSpec
  
  ## extract spectral data for specified TOL band
  ## 173 is our system clipping level for SoundTraps
  ## 206 is the clipping level for the Reson hydrophones
  band_15to17kHz_dB <- (avgSpec[which(freq>15000 & freq<17000)]+clipping_level) # 15-17 kHz band
  band_22to24kHz_dB <- (avgSpec[which(freq>22000 & freq<24000)]+clipping_level) # 22-24 kHz band
  band_45to47kHz_dB <- (avgSpec[which(freq>45000 & freq<47000)]+clipping_level) # 45-47 kHz band
  
  band_16kHz_dB <- (avgSpec[which(freq>lower_freq_16kHz & freq<upper_freq_16kHz)]+clipping_level) # 16 kHz TOL
  band_25kHz_dB <- (avgSpec[which(freq>lower_freq_25kHz & freq<upper_freq_25kHz)]+clipping_level) # 25 kHz TOL
  band_40kHz_dB <- (avgSpec[which(freq>lower_freq_40kHz & freq<upper_freq_40kHz)]+clipping_level) # 40 kHz TOL
  
  ## because dB is on a log scale, we must convert to linear scale and then take the mean
  ## after taking the mean, we can convert back to log scale
  band_15to17kHz_mean_dB <- 20*log10(mean(10^(band_15to17kHz_dB/20))) # 15-17 kHz band
  band_22to24kHz_mean_dB <- 20*log10(mean(10^(band_22to24kHz_dB/20))) # 22-24 kHz band
  band_45to47kHz_mean_dB <- 20*log10(mean(10^(band_45to47kHz_dB/20))) # 45-47 kHz band
  
  band_16kHz_mean_dB <- 20*log10(mean(10^(band_16kHz_dB/20))) # 16 kHz TOL
  band_25kHz_mean_dB <- 20*log10(mean(10^(band_25kHz_dB/20))) # 25 kHz TOL
  band_40kHz_mean_dB <- 20*log10(mean(10^(band_40kHz_dB/20))) # 40 kHz TOL
  
  ## calculate difference between freq bands
  spl_diff_16to23_dB <- band_22to24kHz_mean_dB - band_15to17kHz_mean_dB
  spl_diff_23to46_dB <- band_45to47kHz_mean_dB - band_22to24kHz_mean_dB
  
  spl_diff_16to25_TOL_dB <- band_25kHz_mean_dB - band_16kHz_mean_dB
  spl_diff_25to40_TOL_dB <- band_40kHz_mean_dB - band_25kHz_mean_dB 
  
  ## calculate how many unique clicks are in the dataset
  n_clicks <- nClicks(Acoustic_Study@events[[evNum]], distinct=TRUE) 
  
  ## save mean spectrum
  df_avgSpec <- data.frame(t(avgSpec))
  
  ## extract species ID
  species_id <- Acoustic_Study@events[[evNum]]@species[["id"]]
  
  ## build dataframe with SPL difference and click number data
  df_SPL_diff <- data.frame(eventId=evNum,
                            species=species_id,
                            spl_diff_16to23_dB=spl_diff_16to23_dB, 
                            spl_diff_23to46_dB=spl_diff_23to46_dB,
                            n_dets=n_clicks)
  
  ## join both dataframes
  event_spec_df <- cbind(df_SPL_diff, df_avgSpec)
  
  return(event_spec_df)
}

# create empty data frame to fill
band_diff_df <- data.frame(eventId=c(),species=c(),spl_diff_16to23_dB=c(),
                           spl_diff_23to46_dB=c(),n_dets=c())

for (i in 1:length(Acoustic_Study@events)) {
  # run function to calculate SPL differences
  band_diff_df_tmp <- avgSpec_band_diff(Acoustic_Study, evNum=Acoustic_Study@events[[i]]@id, 
                                        clipping_level, filterfrom_khz)
  # append dataframe
  band_diff_df <- rbind(band_diff_df, band_diff_df_tmp)
}


```


```{r}
## calculate spectra for narwhal events
avSpec_all <- calculateAverageSpectra(fish_dets_0kHzPP_filter,wl=512,evNum=1,
                                      plot=FALSE,sort=FALSE,noise=FALSE,
                                      filterfrom_khz = filterfrom_khz,norm=FALSE)

## extract frequency values and mean spectra
freq <- avSpec_all$freq
avgSpec <- avSpec_all$avgSpec

## extract spectral data for specified TOL band
## 173 is our system clipping level for SoundTraps
## 206 is the clipping level for the Reson hydrophones
band_15to17kHz_dB <- (avgSpec[which(freq>15000 & freq<17000)]+clipping_level) # 15-17 kHz band
band_22to24kHz_dB <- (avgSpec[which(freq>22000 & freq<24000)]+clipping_level) # 22-24 kHz band
band_45to47kHz_dB <- (avgSpec[which(freq>45000 & freq<47000)]+clipping_level) # 45-47 kHz band

band_16kHz_dB <- (avgSpec[which(freq>lower_freq_16kHz & freq<upper_freq_16kHz)]+clipping_level) # 16 kHz TOL
band_25kHz_dB <- (avgSpec[which(freq>lower_freq_25kHz & freq<upper_freq_25kHz)]+clipping_level) # 25 kHz TOL
band_40kHz_dB <- (avgSpec[which(freq>lower_freq_40kHz & freq<upper_freq_40kHz)]+clipping_level) # 40 kHz TOL

## because dB is on a log scale, we must convert to linear scale and then take the mean
## after taking the mean, we can convert back to log scale
band_15to17kHz_mean_dB <- 20*log10(mean(10^(band_15to17kHz_dB/20))) # 15-17 kHz band
band_22to24kHz_mean_dB <- 20*log10(mean(10^(band_22to24kHz_dB/20))) # 22-24 kHz band
band_45to47kHz_mean_dB <- 20*log10(mean(10^(band_45to47kHz_dB/20))) # 45-47 kHz band

band_16kHz_mean_dB <- 20*log10(mean(10^(band_16kHz_dB/20))) # 16 kHz TOL
band_25kHz_mean_dB <- 20*log10(mean(10^(band_25kHz_dB/20))) # 25 kHz TOL
band_40kHz_mean_dB <- 20*log10(mean(10^(band_40kHz_dB/20))) # 40 kHz TOL

## calculate difference between freq bands
spl_diff_16to23_dB <- band_22to24kHz_mean_dB - band_15to17kHz_mean_dB
spl_diff_23to46_dB <- band_45to47kHz_mean_dB - band_22to24kHz_mean_dB

spl_diff_16to25_TOL_dB <- band_25kHz_mean_dB - band_16kHz_mean_dB
spl_diff_25to40_TOL_dB <- band_40kHz_mean_dB - band_25kHz_mean_dB 
```

